### ISSUE TITLE
Changing the library code breaks the public API at the moment

### ISSUE THREAD

**Issue by blundell** [zettaapi/zetta-sdk-android#3]
With our parsing objects being public it means that if we change the parsing we change the signature of the public objects. This is really bad for compatibility and maintainability issues.

This class is an example of a parsing object and a publicly accessible object: https://github.com/zettaapi/zetta-sdk-android/blob/master/zettakit/src/main/java/com/apigee/zettakit/ZIKRoot.java

This could be fixed by having two layers:

```
class ApiZikRoot {
    @Nullable private ZIKLink href;
    @Nullable private ArrayList<ZIKLink> links;
    @Nullable private ArrayList<HashMap> actions;

    @Nullable @JsonProperty("links")
    public ArrayList<ZIKLink> getLinks() {
        return this.links;
    }

   ...
```

and 

```
public class ZikRoot {
    private final ZIKLink href;
    private final List<ZIKLink> links;
    private final List<HashMap> actions;

    public ArrayList<ZIKLink> getLinks() {
        return this.links;
    }
...
```

`ApiZikRoot` would be the api json parsed into an objects then we convert it to our public api `ZikRoot` for public consumption.

```
ZikLink href = apiZikRoot.getHref();
List<ZikLink> links = apiZikRoot.getLinks();
List<HashMap> actions = apiZikRoot.getActions();
return new ZikRoot(href, links, actions);
```

**Comment by RobertWalsh** [comment]
I still really don't see an issue.  Literally all you are doing in the two classes is changing the instance properties to final.  While its nice to have everything final if the instance vars are private with no setters they are already in a sense final.

**Comment by RobertWalsh** [comment]
Also @Nullable and @NonNull are for users of the SDK to warn them when they need to watch out for null vars.  They should be annotated in every single class IMO.

**Comment by blundell** [comment]
I was raising this because I was asked to as future work - not for something that needs doing straight away.

Yeah agree on the annotations, however making a class that avoids anything `nullable` makes a much safer/easier to use API.

**Comment by RobertWalsh** [comment]
For the most part this has been done with the move over to Moshi.  I think that the annotations on the public api classes will/should remain as they cause no harm.  

All methods that return a `Collection` now return empty collections instead of null.  

All other non `Collection` instance property getters may still return however (for instance `ZIKDevice.getName()`).  While we could return just an empty string I'm not sure that is the best way to handle these.  

If you have issues or different opinions please reopen and we can discuss further.
